<title>Registrar</title>
<div class="container" id="register-page">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem; background-color: black">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="svg-logo" fill="#eee"><g><path d="M23.643 4.937c-.835.37-1.732.62-2.675.733.962-.576 1.7-1.49 2.048-2.578-.9.534-1.897.922-2.958 1.13-.85-.904-2.06-1.47-3.4-1.47-2.572 0-4.658 2.086-4.658 4.66 0 .364.042.718.12 1.06-3.873-.195-7.304-2.05-9.602-4.868-.4.69-.63 1.49-.63 2.342 0 1.616.823 3.043 2.072 3.878-.764-.025-1.482-.234-2.11-.583v.06c0 2.257 1.605 4.14 3.737 4.568-.392.106-.803.162-1.227.162-.3 0-.593-.028-.877-.082.593 1.85 2.313 3.198 4.352 3.234-1.595 1.25-3.604 1.995-5.786 1.995-.376 0-.747-.022-1.112-.065 2.062 1.323 4.51 2.093 7.14 2.093 8.57 0 13.255-7.098 13.255-13.254 0-.2-.005-.402-.014-.602.91-.658 1.7-1.477 2.323-2.41z"></path></g></svg>
        </div>

        <div class="row">
          <div class="col">
            <h2 style="color: #eee">Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/register" method="post">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Nome" name="name"  value="<?= $this->view->user['name'] ?>">
              </div>
              
              <div class="form-group">
                <input type="email" class="form-control" placeholder="E-mail" name="email" value="<?= $this->view->user['email'] ?>">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Link da img" name="img">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Senha" name="password">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text text-white">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              <?php if($this->view->erroRegister) {?>
                <small class="form-text text-danger text-center">Erro ao tentar realizar o cadastro</small>
              <?php }?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  