<title>Seguir</title>
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logout">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo animate__animated animate__bounce">
						<div class="row">
							<div class="col">
								<div class="d-flex justify-content-center align-center">
									<img src="https://images.unsplash.com/photo-1622757315689-a4e88eff699b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" style="border-radius: 5rem; width: 80px; height: 80px; margin-top: .5rem;" class="">
								</div>
							</div>

						</div>
					</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$this->view->username ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalTweets['total'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalFollowing['total'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalFollowers['total'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/follow">
								<div class="input-group mb-3">
									<input type="text" class="form-control" placeholder="Quem você está procurando?" name="followUs">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->users as $key => $value) {?>
				<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-6">
									<?=$value['nome'] ?>
								</div>
							
								<div class="col-md-6 d-flex justify-content-end">
									<div>
										<?php if($value['isFollowing'] == 0){ ?>
											<a href="/action?action=follow&user_id=<?= $value['id'] ?>" class="btn btn-success">Seguir</a>
										<?php  } ?>
										<?php if($value['isFollowing'] == 1){ ?>
										<a href="/action?action=unfollow&user_id=<?= $value['id'] ?>" class="btn btn-danger">Deixar de seguir</a>
										<?php  } ?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php } ?>

		</div>
	</div>
</div>