<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logout">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo animate__animated animate__bounce">
					<div class="row">
						<div class="col">
							<div class="d-flex justify-content-center align-center">
								<img src="https://images.unsplash.com/photo-1622757315689-a4e88eff699b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" style="border-radius: 5rem; width: 80px; height: 80px; margin-top: .5rem;" class="">
							</div>
						</div>

					</div>
				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['name']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="post">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $id_usuario => $tweet) {?>

			<div class="row tweet">
				<div class="col">
					<p><strong><?= $tweet['nome']?></strong> <small><span class="text text-muted"><?= $tweet['data']?></span></small></p>
					<p><?= $tweet['tweet']?></p>

					<br />
					<?php if($tweet['id_usuario'] == $_SESSION['id']) {?>
						<form action="/delete" method="POST">
							<div class="col d-flex justify-content-end">
								<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								<input type="hidden" name="id_user" value="<?= $_SESSION['id'] ?>">
								<input type="hidden" name="id_tweet" value="<?= $tweet['id'] ?>">
							</div>
						</form>	
					<?php }?>	
				</div>
			</div>
			<?php } ?>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/follow" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>